### ISSUE TITLE
这个框架的数据库操作疑问

### ISSUE THREAD

**Issue by eedba** [betephp/betephp#1]
现在项目远不止查询单条或单条信息，如果在使用联表，多条件的时候bete中应如何写 。
例如实现
select a.id,b.name from table a left join table2 b on b.id=a.id where a.id=1 
又或是多条件的状态
select * from table a=1 and (b=1 or c=1) or d=1 类似这些复杂的 and or 时，要如何写那个，我看文档上无介绍。只是简单常见的sql拼写。

**Comment by eccozhou** [comment]
这种建议使用`whereRaw()`，手工拼接SQL。

**Comment by Jaackie** [comment]
是否有考虑过验证器的规则字符串来个validatorBuilder呢
`'name' => 'required|chinese|between:2,20',`
可以写成:
`'name' => VB::required()->chinese()->between(2,20)->toString(),`
我不知道你们实际在生产中怎样去写验证规则的, 但如果是每个去写一遍这个字符串的, 那就略显生猛了.

当然验证器和规则甚至也可以耦合在一起直接得其值:
`$age = V::post('age')->required()->between(0)->toInt();`
